SELECT 
    CASE
         WHEN g.GRADE > 7 THEN S.name
         ELSE NULL
    END AS NAME_, g.GRADE, s.MARKS
FROM STUDENTS as s
INNER JOIN GRADES g
    ON s.MARKS BETWEEN g.MIN_MARK AND g.MAX_MARK
ORDER  BY g.GRADE DESC, NAME_ ASC, s.MARKS ASC;