SELECT s.HACKER_ID, h.NAME
FROM HACKERS AS h
INNER JOIN SUBMISSIONS AS s ON h.HACKER_ID = s.HACKER_ID
INNER JOIN CHALLENGES AS c ON c.CHALLENGE_ID = s.CHALLENGE_ID
INNER JOIN DIFFICULTY AS d ON d.DIFFICULTY_LEVEL = c.DIFFICULTY_LEVEL
WHERE s.SCORE = d.SCORE
GROUP BY S.HACKER_ID, h.NAME
HAVING COUNT(s.HACKER_ID) > 1
ORDER BY count(s.HACKER_ID) DESC, s.HACKER_ID ASC;