SELECT BST.N,
    CASE
        WHEN BST.P IS NULL THEN 'Root'
        WHEN NOT EXISTS (SELECT B.P FROM BST AS B WHERE B.P = BST.N) THEN 'Leaf'    
        ELSE 'Inner'    
    END
FROM BST
ORDER BY BST.N;