----------------------- VER 1 ----------------------- 
SELECT e.COMPANY_CODE, c.FOUNDER, COUNT(DISTINCT e.LEAD_MANAGER_CODE), COUNT(DISTINCT e.SENIOR_MANAGER_CODE), COUNT(DISTINCT e.MANAGER_CODE), COUNT(DISTINCT e.EMPLOYEE_CODE)
FROM COMPANY AS c 

INNER JOIN EMPLOYEE AS e ON e.COMPANY_CODE = c.COMPANY_CODE
INNER JOIN LEAD_MANAGER AS lm ON e.LEAD_MANAGER_CODE = lm.LEAD_MANAGER_CODE
INNER JOIN SENIOR_MANAGER AS sm ON e.SENIOR_MANAGER_CODE = sm.SENIOR_MANAGER_CODE
INNER JOIN MANAGER AS m ON e.MANAGER_CODE = m.MANAGER_CODE

GROUP BY e.COMPANY_CODE, c.FOUNDER
ORDER BY e.COMPANY_CODE ASC;


----------------------- VER 2 -----------------------
SELECT e.COMPANY_CODE, c.FOUNDER, COUNT(DISTINCT e.LEAD_MANAGER_CODE), COUNT(DISTINCT e.SENIOR_MANAGER_CODE), COUNT(DISTINCT e.MANAGER_CODE), COUNT(DISTINCT e.EMPLOYEE_CODE)
FROM COMPANY AS c, LEAD_MANAGER AS lm, SENIOR_MANAGER AS sm, MANAGER AS m, EMPLOYEE AS e

WHERE e.COMPANY_CODE = c.COMPANY_CODE
AND e.LEAD_MANAGER_CODE = lm.LEAD_MANAGER_CODE
AND e.SENIOR_MANAGER_CODE = sm.SENIOR_MANAGER_CODE
AND e.MANAGER_CODE = m.MANAGER_CODE

GROUP BY e.COMPANY_CODE, c.FOUNDER
ORDER BY e.COMPANY_CODE ASC;