SELECT NAME + '(' + 
    CASE
        WHEN OCCUPATION = 'DOCTOR' THEN 'D'
        WHEN OCCUPATION = 'ACTOR' THEN 'A'
        WHEN OCCUPATION = 'PROFESSOR' THEN 'P'
        WHEN OCCUPATION = 'SINGER' THEN 'S'
    END + ')'
FROM OCCUPATIONS
ORDER BY NAME ASC;